### ISSUE TITLE
SRB Decoupler has reflection issues

### ISSUE THREAD

**Issue by daedaelus** [Jeast85/CSS-unofficial#13]
The SRB decouple on the SLS has a "glitter" like reflection.

**Comment by MrMikeNZ** [comment]
This wad fixed. Old version used?
I will apply jeasts fixes to my  install and upload. Im working off updated 1.7 that   is not uploaded.

**Comment by daedaelus** [comment]
When a new version is released i am using a clean install from this repository. I Downloaded the CSS and Onepiece fresh from this github. Should i be using your CSS and his Onepiece?

**Comment by MrMikeNZ** [comment]
Part replaced
