### ISSUE TITLE
[Onepiece] Rear RCS not operating properly

### ISSUE THREAD

**Issue by daedaelus** [Jeast85/CSS-unofficial#15]
Rear RCS pods are not balanced with front and barely are displaying any actions. Or thruster animations when using RCS.

**Comment by daedaelus** [comment]
The issue resolved itself on another maneuver looks to be working fine now. Closing Issue.

**Comment by MrMikeNZ** [comment]
What version off ksp and css are you using?  I dont have this many issues. ...

**Comment by MrMikeNZ** [comment]
What version off ksp and css are you using?  I dont have this many issues. ...
