### ISSUE TITLE
[Onepiece] Glide is a little rough

### ISSUE THREAD

**Issue by daedaelus** [Jeast85/CSS-unofficial#18]
The shuttle was designed as a glider. 

As it is heavy it really did not glide well when it entered about 2k above the surface. It basically just dropped on approach the minute it entered low altitude even on a good approach it just lost altitude as if it was a stall with good speed. Earlier models (a patch to 1.6) some google docs update had the glide spot on.

**Comment by MrMikeNZ** [comment]
This is in every way different than the normal version.  Ksp 1.0.4 maybe?

Concusion: one piece to be removed/canceled due to purely negative results, impact on gameplay

**Comment by daedaelus** [comment]
Im not sure what all changed in 1.0.4 but i am using the steam version so it is up to date. This is entirely your decision mike ill back any play you make 100%.

**Comment by Jeast85** [comment]
1.0.4 changed the aero quite a bit yes. I have updated the aero in 1.6.0.2 where it glides like a brick again. Would you be so kind daedaelus to give that a try as well?

**Comment by MrMikeNZ** [comment]
I read 1.0.4 changed only game save fixes.

Have you seen the cfg for the one piece?  Its only a lift surface... I have only made 1 change and need  more time to adjust.  It is too buggy with the current version of css so wont recomend people use it yet without my setup. I will update all I have with yours then go from there

**Comment by Jeast85** [comment]
Yes the change itself was in 1.0.3 but they released 1.04 within a day after.

-------- Oorspronkelijk bericht --------
Van: MrMikeNZ <notifications@github.com>
Datum: 26-06-2015  08:45  (GMT+01:00)
Aan: Jeast85/CSS-unofficial <CSS-unofficial@noreply.github.com>
Cc: Jeast85 <cardieast@hotmail.com>
Onderwerp: Re: [CSS-unofficial] [Onepiece] Glide is a little rough (#18)

I read 1.0.4 changed only game save fixes.

Have you seen the cfg for the one piece?  Its only a lift surface... I have only made 1 change and need  more time to adjust.  It is too buggy with the current version of css so wont recomend people use it yet without my setup. I will update all I have with yours then go from there

---

**Comment by MrMikeNZ** [comment]
@jeast. Did you change aero for the multi piece or the one piece? I need to actually play ksp and use the shuttle

**Comment by Jeast85** [comment]
Just the multi piece.

 

If I can give you some advice, copy your KSP folder and only leave the relevant CSS folders so it loads faster.

When you are ingame you test your stuff out, alt-tab out to make changes, go back to KSP when done, go to the space center screen and press alt+f11. Now you can reload al MM modules without restarting the game.

**Comment by Jeast85** [comment]
Do you want me to take on the flying part of the one piece so you can focus on the model/textures/modules?

**Comment by MrMikeNZ** [comment]
Is it not alt f12 then reload all after alt tab changes to files. Is what I do. Bit I dont often go into the game I spend too much time modeling. So 4 hours modeling then 10 min game then start again tomorow.

I need more game time. Also I dont have mm patches relating to my work.

Will have some progress this weekend. Starting in  a few hours. Atleast have a stable one piece finally

**Comment by Jeast85** [comment]
Yes indeed.

I often make a quicksave during reentry so I can test that part specificly.

**Comment by MrMikeNZ** [comment]
Good call. Yeah if you have time you can do the aero on one piece... I need to update to 1.0.4.
also your game directory might be different to mine so textureswitch wont work like with daedaelus

**Comment by Jeast85** [comment]
I’ll only do the flying part and leave the testing of other stuff to daedaelus (what he is doing great btw!!)

**Comment by MrMikeNZ** [comment]
What is a good live chat program to use?

**Comment by Jeast85** [comment]
Steam haha

**Comment by MrMikeNZ** [comment]
I dont have steam

**Comment by Jeast85** [comment]
IRC, --> hexchat

**Comment by MrMikeNZ** [comment]
Is that on android?

**Comment by Jeast85** [comment]
No PC

**Comment by MrMikeNZ** [comment]
Ok I will do that but I spend most time commenting while on my phone

**Comment by Jeast85** [comment]
I think its works best when you first finish all the work on the cfg’s and when that’s done I go in to do the aero.

**Comment by MrMikeNZ** [comment]
1.0.4 aero updates from jeasts latest have been applied to my install.
more fixes made to one piece

**Comment by daedaelus** [comment]
So i am clear what to test can you guys tell me what CSS package to use as if it was a clean install? I am currently the one listed at https://github.com/Jeast85/CSS-unofficial/tree/MIKE Should i be testing "master"? It seems im missing things and i want to make sure i test the right stuff.

**Comment by MrMikeNZ** [comment]
I will upload a 1.7 release soon with onepiece to github. I need to check I will not be missing out jeasts work on it

**Comment by MrMikeNZ** [comment]
installing hexchat now

**Comment by daedaelus** [comment]
I also have hexchat aka IRC what server are we using?

**Comment by MrMikeNZ** [comment]
Um I will let you know when I get home.

**Comment by MrMikeNZ** [comment]
Um I will let you know when I get home. 
I have skype now. Mike.quinn_nz is my name I made for it

**Comment by daedaelus** [comment]
I added you :)

**Comment by MrMikeNZ** [comment]
I dont see you. Msg me maybe or tell me ur Skype name?

**Comment by MrMikeNZ** [comment]
New upload. Restart issues there
