### ISSUE TITLE
Jeast

### ISSUE THREAD

**Issue by MrMikeNZ** [Jeast85/CSS-unofficial#19]
Can you remove one piece I cant do it on my  github

**Comment by Jeast85** [comment]
Are you sure Mike?

-------- Oorspronkelijk bericht --------
Van: MrMikeNZ <notifications@github.com>
Datum: 25-06-2015  23:33  (GMT+01:00)
Aan: Jeast85/CSS-unofficial <CSS-unofficial@noreply.github.com>
Onderwerp: [CSS-unofficial] Jeast (#19)

Can you remove one piece I cant do it on my  github

---
Reply to this email directly or view it on GitHub:
https://github.com/Jeast85/CSS-unofficial/issues/19
