### ISSUE TITLE
Monoprop

### ISSUE THREAD

**Issue by Jeast85** [Jeast85/CSS-unofficial#6]
The 1800 monopropellant is not enough. It takes around 1700 to do a deorbit burn from a 200 km orbit.

**Comment by MrMikeNZ** [comment]
Maybe increase its efficiency so id doesnt burn up as fast?

**Comment by Jeast85** [comment]
I tried some ISP settings but to no avail. The thrust setting seems fine to me but tuning up the ISP didn't do much.

**Comment by Jeast85** [comment]
The OMS fuel dump is placed in the stock craft, this is the problem.
