### ISSUE TITLE
[Onepiece] Textures missing from wings

### ISSUE THREAD

**Issue by daedaelus** [Jeast85/CSS-unofficial#9]
Wing Textures are not displaying

**Comment by MrMikeNZ** [comment]
There must be a mixup brtween my install and yours. Like changed directories. I have no issues. What version of css are you using?

**Comment by daedaelus** [comment]
Downloaded clean install from https://github.com/Jeast85/CSS-unofficial/tree/MIKE bottom right corner download zip.

**Comment by daedaelus** [comment]
Do you have a steam or skype we can talk in real time on?

**Comment by MrMikeNZ** [comment]
Fixed
